// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/account/[name].tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/signup.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/FirstIsland.tsx";
import * as $$2 from "./islands/Login.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/account/[name].tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/signup.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/FirstIsland.tsx": $$1,
    "./islands/Login.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
